### ISSUE TITLE
Extension won't load on iPad

### ISSUE THREAD

**Issue by johan-gorter** [KitronikLtd/pxt-kitronik-simple-servo#5]
I succesfully used the extension on desktop and Android, but my students will have iPads and unfortunately when clicking on the extension, nothing happens and the extension screen resets itself.

I have looked through the typescript file but could not find anything that is unsupported on Safari. The only suspicous thing I found was `Math.map` which does not normally exist anywhere. There is a `pins.map` function provided by makeCode that would probably have the same semantics.

I tried to load other extensions and most of them seem to be working fine on the iPad.

I really like the board by the way and also like the fact that there are dutch translations for the extension. Thank you.

**Comment by DaveAtKitronik** [comment]
What version of iOS / iPads are you using?
Just checking you are using the webpage https://makecode.microbit.org not the iOS app?
We will try to reproduce

**Comment by johan-gorter** [comment]
I am using the app. Ipad air second generation, updated as far as possible.

Op di 17 jan. 2023 09:31 schreef DaveAtKitronik ***@***.***>:

**Comment by JackAtKitronik** [comment]
Hi, we have failed to reproduce this issue.

Can you let us know if you managed to solve your problem?
And if you did, what fixed your issue?

**Comment by johan-gorter** [comment]
https://photos.app.goo.gl/FWzqbw54UcYMaHeQ9

The problem still occurs, see the video. I expect the problem to be on the makecode side.
I had the children use the low level 'write servo pin' instruction on pin 8, 15 and 16.

**Comment by JackAtKitronik** [comment]
Should be fixed now.

See [here](https://github.com/microsoft/pxt-microbit/issues/4959#event-9237280320)
